version: "3.8"
name: "log-archive-tool"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
